@startuml

title __ELEMENTS's Class Diagram__\n

  namespace es.ull.patrones.practica3 {
    namespace Elements {
      interface es.ull.patrones.practica3.Elements.Ball {
          {abstract} + getDescription()
          {abstract} + throwBall()
      }
    }
  }
  

  namespace es.ull.patrones.practica3 {
    namespace Elements {
      interface es.ull.patrones.practica3.Elements.Footwear {
          {abstract} + getDescription()
          {abstract} + putOn()
      }
    }
  }
  

  namespace es.ull.patrones.practica3 {
    namespace Elements {
      class es.ull.patrones.practica3.Elements.PadelBall {
          - image : File
          - name : String
          - price : double
          - stock : int
          + PadelBall()
          + PadelBall()
          + getDescription()
          + getImageName()
          + getName()
          + getPrice()
          + getStock()
          + showImage()
          + throwBall()
      }
    }
  }
  

  namespace es.ull.patrones.practica3 {
    namespace Elements {
      class es.ull.patrones.practica3.Elements.PadelFootwear {
          - image : String
          - name : String
          - price : double
          - stock : int
          + PadelFootwear()
          + PadelFootwear()
          + getDescription()
          + getImageName()
          + getName()
          + getPrice()
          + getStock()
          + putOn()
      }
    }
  }
  

  namespace es.ull.patrones.practica3 {
    namespace Elements {
      class es.ull.patrones.practica3.Elements.PadelTShirt {
          - image : String
          - name : String
          - price : double
          - stock : int
          + PadelTShirt()
          + PadelTShirt()
          + getDescription()
          + getImageName()
          + getName()
          + getPrice()
          + getStock()
          + wearTShirt()
      }
    }
  }
  

  namespace es.ull.patrones.practica3 {
    namespace Elements {
      interface es.ull.patrones.practica3.Elements.TShirt {
          {abstract} + getDescription()
          {abstract} + wearTShirt()
      }
    }
  }
  

  es.ull.patrones.practica3.Elements.PadelBall .up.|> es.ull.patrones.practica3.Elements.Ball
  es.ull.patrones.practica3.Elements.PadelFootwear .up.|> es.ull.patrones.practica3.Elements.Footwear
  es.ull.patrones.practica3.Elements.PadelTShirt .up.|> es.ull.patrones.practica3.Elements.TShirt


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
